service: sqs

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  
functions:
  hello:
    handler: publisher.handler
    environment:
      SQSqueueName: !Ref MyQueue
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"