service: sqs

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 10 
  
functions:
  publisher:
    handler: publisher.handler
    environment:
      SQSqueueName: !Ref MyQueue
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
          batchSize: 10

  consumer:
    handler: consumer.handler
    environment:
      SQSqueueName: !Ref MyQueue
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
          batchSize: 10

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"

    SampleSQSPolicy: 
      Type: AWS::SQS::QueuePolicy
      Properties: 
        Queues: 
          - !Ref MyQueue
        PolicyDocument: 
          Statement: 
            - 
              Action: 
                - "SQS:SendMessage" 
                - "SQS:ReceiveMessage"
                - "SQS:ChangeMessageVisibility"
                - "SQS:DeleteMessage"
                - "SQS:GetQueueAttributes"
              Effect: "Allow"
              Resource: !GetAtt MyQueue.Arn
              Principal:  
                AWS: 
                  - !Ref "AWS::AccountId"